default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Dockerを使わないときはコメントアウト
  # host: db
  # username: postgres
  # password: password

development:
  <<: *default
  database: SafeKids_development

test:
  <<: *default
  database: SafeKids_test

production:
  <<: *default
  database: SafeKids_production
  username: SafeKids
  password: <%= ENV['SAFEKIDS_DATABASE_PASSWORD'] %>
