default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SafeKids_development
  # Dockerを使わないときはコメントアウト
  # host: db
  # username: postgres
  # password: password

test:
  <<: *default
  database: SafeKids_test

production:
  <<: *default
  database: SafeKids_production
  username: SafeKids
  password: <%= ENV['SAFEKIDS_DATABASE_PASSWORD'] %>
  # host: <%= Rails.application.credentials.rds[:host] %>
  # database: <%= Rails.application.credentials.rds[:database] %>
  # username: <%= Rails.application.credentials.rds[:username] %>
  # password: <%= Rails.application.credentials.rds[:password] %>
