default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    # Dockerを使わないときはコメントアウト
  # username: postgres
  # password: password

development:
  <<: *default
  database: SafeKids_development
  host: db

test:
  <<: *default
  database: SafeKids_test

production:
  <<: *default
  database: SafeKids_production
  username: SafeKids
  password: <%= ENV['SAFEKIDS_DATABASE_PASSWORD'] %>
  port: 5432
