default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  host: 127.0.0.1
  username: postgres
  password: password
  database: SafeKids_test
